#!/usr/bin/env python3
"""
Generate frontend/lib/summa-articles.ts from the database.

Run after import_summa.py has populated the DB:
    cd backend
    python -m scripts.generate_articles_ts
"""

import asyncio
import json
import sys
from pathlib import Path

import asyncpg

sys.path.insert(0, str(Path(__file__).parent.parent))
from app.core.config import settings

OUTPUT = Path(__file__).parent.parent.parent / "frontend" / "lib" / "summa-articles.ts"

PART_ORDER = ["prima-pars", "prima-secundae", "secunda-secundae", "tertia-pars"]


async def main():
    if not settings.DATABASE_URL:
        print("ERROR: DATABASE_URL not set in .env")
        sys.exit(1)

    pool = await asyncpg.create_pool(settings.DATABASE_URL)
    rows = await pool.fetch(
        """
        SELECT part_id, question_n, article_n, article_title
        FROM summa_articles
        ORDER BY part_id, question_n, article_n
        """
    )
    await pool.close()

    data: dict[str, dict[int, list[dict]]] = {}
    for row in rows:
        part, q = row["part_id"], row["question_n"]
        data.setdefault(part, {}).setdefault(q, []).append(
            {"n": row["article_n"], "title": row["article_title"]}
        )

    lines = [
        "// Auto-generated by scripts/generate_articles_ts.py — do not edit manually.",
        "// Run: cd backend && python -m scripts.generate_articles_ts",
        "",
        "export const SUMMA_ARTICLE_TITLES: Record<string, Record<number, { n: number; title: string }[]>> = {",
    ]

    for part_id in PART_ORDER:
        if part_id not in data:
            continue
        lines.append(f'  "{part_id}": {{')
        for q_n in sorted(data[part_id]):
            articles = data[part_id][q_n]
            items = ", ".join(
                f'{{n:{a["n"]},title:{json.dumps(a["title"])}}}'
                for a in articles
            )
            lines.append(f"    {q_n}: [{items}],")
        lines.append("  },")

    lines += ["};", ""]

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(rows)} articles → {OUTPUT}")


if __name__ == "__main__":
    asyncio.run(main())
