export interface SummaQuestion {
  n: number;
  title: string;
  articles: number;
}

export interface SummaTreatise {
  label: string;
  questions: SummaQuestion[];
}

export interface SummaPart {
  id: string;
  label: string;
  abbr: string;
  treatises: SummaTreatise[];
}

export interface SelectedNode {
  partId: string;
  partLabel: string;
  partAbbr: string;
  questionN: number;
  questionTitle: string;
  articleN?: number;
}

export const SUMMA_PARTS: SummaPart[] = [
  {
    id: "prima-pars",
    label: "Prima Pars",
    abbr: "ST I",
    treatises: [
      {
        label: "Treatise on Sacred Doctrine",
        questions: [
          { n: 1, title: "The Nature and Extent of Sacred Doctrine", articles: 10 },
        ],
      },
      {
        label: "Treatise on The One God",
        questions: [
          { n: 2, title: "The Existence of God", articles: 3 },
          { n: 3, title: "The Simplicity of God", articles: 8 },
          { n: 4, title: "The Perfection of God", articles: 3 },
          { n: 5, title: "Goodness in General", articles: 6 },
          { n: 6, title: "The Goodness of God", articles: 4 },
          { n: 7, title: "The Infinity of God", articles: 4 },
          { n: 8, title: "The Existence of God in Things", articles: 4 },
          { n: 9, title: "The Immutability of God", articles: 2 },
          { n: 10, title: "The Eternity of God", articles: 6 },
          { n: 11, title: "The Unity of God", articles: 4 },
          { n: 12, title: "How God is Known by Us", articles: 13 },
          { n: 13, title: "The Names of God", articles: 12 },
          { n: 14, title: "The Knowledge of God", articles: 16 },
          { n: 15, title: "Ideas", articles: 3 },
          { n: 16, title: "Truth", articles: 8 },
          { n: 17, title: "Falsity", articles: 4 },
          { n: 18, title: "The Life of God", articles: 4 },
          { n: 19, title: "The Will of God", articles: 12 },
          { n: 20, title: "God's Love", articles: 4 },
          { n: 21, title: "The Justice and Mercy of God", articles: 4 },
          { n: 22, title: "The Providence of God", articles: 4 },
          { n: 23, title: "Predestination", articles: 8 },
          { n: 24, title: "The Book of Life", articles: 3 },
          { n: 25, title: "The Power of God", articles: 6 },
          { n: 26, title: "The Divine Beatitude", articles: 4 },
        ],
      },
      {
        label: "Treatise on The Most Holy Trinity",
        questions: [
          { n: 27, title: "The Procession of the Divine Persons", articles: 5 },
          { n: 28, title: "The Divine Relations", articles: 4 },
          { n: 29, title: "The Divine Persons", articles: 4 },
          { n: 30, title: "The Plurality of Persons in God", articles: 4 },
          { n: 31, title: "Unity and Plurality in God", articles: 4 },
          { n: 32, title: "The Knowledge of the Divine Persons", articles: 4 },
          { n: 33, title: "The Person of the Father", articles: 4 },
          { n: 34, title: "The Person of the Son", articles: 3 },
          { n: 35, title: "The Image", articles: 2 },
          { n: 36, title: "The Person of the Holy Spirit", articles: 4 },
          { n: 37, title: "The Name of the Holy Spirit: Love", articles: 2 },
          { n: 38, title: "The Name of the Holy Spirit: Gift", articles: 2 },
          { n: 39, title: "The Persons in Relation to the Essence", articles: 8 },
          { n: 40, title: "The Persons as Compared to the Relations", articles: 4 },
          { n: 41, title: "The Persons in Relation to Notional Acts", articles: 6 },
          { n: 42, title: "Equality and Likeness of the Divine Persons", articles: 6 },
          { n: 43, title: "The Mission of the Divine Persons", articles: 8 },
        ],
      },
      {
        label: "Treatise on The Creation",
        questions: [
          { n: 44, title: "The Procession of Creatures from God", articles: 4 },
          { n: 45, title: "The Mode of Emanation of Things from God", articles: 8 },
          { n: 46, title: "The Beginning of the Duration of Creatures", articles: 3 },
        ],
      },
      {
        label: "Treatise on The Distinction of Things in General",
        questions: [
          { n: 47, title: "The Distinction of Things in General", articles: 3 },
        ],
      },
      {
        label: "Treatise on The Distinction of Good and Evil",
        questions: [
          { n: 48, title: "The Distinction of Good and Evil", articles: 6 },
          { n: 49, title: "The Cause of Evil", articles: 3 },
        ],
      },
      {
        label: "Treatise on The Angels",
        questions: [
          { n: 50, title: "The Substance of the Angels", articles: 5 },
          { n: 51, title: "The Angels in Comparison with Bodies", articles: 3 },
          { n: 52, title: "The Angels in Relation to Place", articles: 3 },
          { n: 53, title: "The Local Movement of Angels", articles: 3 },
          { n: 54, title: "The Knowledge of the Angels", articles: 5 },
          { n: 55, title: "The Medium of Angelic Knowledge", articles: 3 },
          { n: 56, title: "The Knowledge of Angels of Immaterial Things", articles: 3 },
          { n: 57, title: "The Knowledge of Angels of Material Things", articles: 5 },
          { n: 58, title: "The Mode of Angelic Knowledge", articles: 7 },
          { n: 59, title: "The Will of the Angels", articles: 4 },
          { n: 60, title: "The Love of the Angels", articles: 5 },
          { n: 61, title: "The Production of Angels in the Natural Order", articles: 4 },
          { n: 62, title: "The Perfection of the Angels in Grace and Glory", articles: 9 },
          { n: 63, title: "The Malice of the Angels with Regard to Sin", articles: 9 },
          { n: 64, title: "The Punishment of the Demons", articles: 4 },
        ],
      },
      {
        label: "Treatise on The Work of the Six Days",
        questions: [
          { n: 65, title: "The Work of Creation of Corporeal Creatures", articles: 4 },
          { n: 66, title: "The Order of Creation Towards Distinction", articles: 4 },
          { n: 67, title: "The Work of Distinction in Itself", articles: 4 },
          { n: 68, title: "The Work of the Second Day", articles: 4 },
          { n: 69, title: "The Work of the Third Day", articles: 2 },
          { n: 70, title: "The Work of Adornment: The Fourth Day", articles: 3 },
          { n: 71, title: "The Work of the Fifth Day", articles: 1 },
          { n: 72, title: "The Work of the Sixth Day", articles: 1 },
          { n: 73, title: "The Seventh Day", articles: 3 },
          { n: 74, title: "All the Seven Days in Common", articles: 3 },
        ],
      },
      {
        label: "Treatise on Man",
        questions: [
          { n: 75, title: "The Essence of the Soul", articles: 7 },
          { n: 76, title: "The Union of Soul and Body", articles: 8 },
          { n: 77, title: "The Powers of the Soul in General", articles: 8 },
          { n: 78, title: "The Specific Powers of the Soul", articles: 4 },
          { n: 79, title: "The Intellectual Powers", articles: 13 },
          { n: 80, title: "The Appetitive Powers in General", articles: 2 },
          { n: 81, title: "The Power of Sensuality", articles: 3 },
          { n: 82, title: "The Will", articles: 5 },
          { n: 83, title: "Free Will", articles: 4 },
          { n: 84, title: "How the Soul Knows Bodies", articles: 8 },
          { n: 85, title: "The Mode and Order of Understanding", articles: 8 },
          { n: 86, title: "What Our Intellect Knows in Material Things", articles: 4 },
          { n: 87, title: "How the Intellectual Soul Knows Itself", articles: 4 },
          { n: 88, title: "How the Human Soul Knows What is Above Itself", articles: 3 },
          { n: 89, title: "The Knowledge of the Separated Soul", articles: 8 },
          { n: 90, title: "The First Production of Man's Soul", articles: 4 },
          { n: 91, title: "The Production of the First Man's Body", articles: 4 },
          { n: 92, title: "The Production of Woman", articles: 4 },
          { n: 93, title: "The End or Term of Man's Production: Image of God", articles: 9 },
          { n: 94, title: "The Condition and Knowledge of the First Man", articles: 4 },
          { n: 95, title: "Things Pertaining to the First Man's Will: Grace and Righteousness", articles: 4 },
          { n: 96, title: "The Mastership of Man in the State of Innocence", articles: 4 },
          { n: 97, title: "The Preservation of the Individual", articles: 4 },
          { n: 98, title: "The Preservation of the Species", articles: 2 },
          { n: 99, title: "The Condition of Offspring as to Body", articles: 2 },
          { n: 100, title: "The Condition of Offspring as to Righteousness", articles: 2 },
          { n: 101, title: "The Condition of Offspring as to Knowledge", articles: 2 },
          { n: 102, title: "The Abode of Man: Paradise", articles: 4 },
        ],
      },
      {
        label: "Treatise on The Conservation and Government of Creatures",
        questions: [
          { n: 103, title: "The Government of Things in General", articles: 8 },
          { n: 104, title: "The Special Effects of Divine Government", articles: 4 },
          { n: 105, title: "The Change of Creatures by God", articles: 8 },
          { n: 106, title: "How One Creature Moves Another", articles: 4 },
          { n: 107, title: "The Speech of the Angels", articles: 5 },
          { n: 108, title: "The Angelic Degrees: Hierarchies and Orders", articles: 8 },
          { n: 109, title: "The Ordering of the Bad Angels", articles: 4 },
          { n: 110, title: "How Angels Act on Bodies", articles: 4 },
          { n: 111, title: "The Action of Angels on Man", articles: 4 },
          { n: 112, title: "The Mission of Angels", articles: 4 },
          { n: 113, title: "The Guardianship of the Good Angels", articles: 8 },
          { n: 114, title: "The Assaults of the Demons", articles: 5 },
          { n: 115, title: "The Action of Corporeal Creatures", articles: 6 },
          { n: 116, title: "Fate", articles: 4 },
          { n: 117, title: "Things Pertaining to the Action of Man", articles: 4 },
          { n: 118, title: "The Production of Man from Man as to the Soul", articles: 3 },
          { n: 119, title: "The Propagation of Man as to the Body", articles: 2 },
        ],
      },
    ],
  },

  {
    id: "prima-secundae",
    label: "Prima Secundae",
    abbr: "ST I-II",
    treatises: [
      {
        label: "Treatise on The Last End",
        questions: [
          { n: 1, title: "Man's Last End", articles: 8 },
          { n: 2, title: "Those Things in Which Man's Happiness Consists", articles: 8 },
          { n: 3, title: "What is Happiness", articles: 8 },
          { n: 4, title: "Things Required for Happiness", articles: 8 },
          { n: 5, title: "The Attainment of Happiness", articles: 8 },
        ],
      },
      {
        label: "Treatise on Human Acts",
        questions: [
          { n: 6, title: "The Voluntary and the Involuntary", articles: 8 },
          { n: 7, title: "Circumstances of Human Acts", articles: 4 },
          { n: 8, title: "The Will: Objects of Volition", articles: 3 },
          { n: 9, title: "The Mover of the Will", articles: 6 },
          { n: 10, title: "The Manner in Which the Will is Moved", articles: 4 },
          { n: 11, title: "Enjoyment", articles: 4 },
          { n: 12, title: "Intention", articles: 5 },
          { n: 13, title: "Choice", articles: 6 },
          { n: 14, title: "Counsel", articles: 6 },
          { n: 15, title: "Consent", articles: 4 },
          { n: 16, title: "Use", articles: 4 },
          { n: 17, title: "Acts Commanded by the Will", articles: 9 },
          { n: 18, title: "The Good and Evil of Human Acts in General", articles: 11 },
          { n: 19, title: "The Goodness and Malice of Interior Acts", articles: 10 },
          { n: 20, title: "Goodness and Malice in Exterior Acts", articles: 6 },
          { n: 21, title: "The Consequences of Human Acts: Merit and Demerit", articles: 4 },
        ],
      },
      {
        label: "Treatise on The Passions",
        questions: [
          { n: 22, title: "The Subject of the Soul's Passions", articles: 3 },
          { n: 23, title: "How the Passions Differ from One Another", articles: 4 },
          { n: 24, title: "Good and Evil in the Passions of the Soul", articles: 4 },
          { n: 25, title: "The Order of Passions to One Another", articles: 4 },
          { n: 26, title: "Love", articles: 4 },
          { n: 27, title: "The Cause of Love", articles: 4 },
          { n: 28, title: "The Effects of Love", articles: 6 },
          { n: 29, title: "Hatred", articles: 6 },
          { n: 30, title: "Concupiscence", articles: 4 },
          { n: 31, title: "Pleasure in Itself", articles: 8 },
          { n: 32, title: "The Causes of Pleasure", articles: 8 },
          { n: 33, title: "The Effects of Pleasure", articles: 4 },
          { n: 34, title: "The Goodness and Malice of Pleasures", articles: 4 },
          { n: 35, title: "Pain or Sorrow in Itself", articles: 8 },
          { n: 36, title: "The Causes of Sorrow or Pain", articles: 4 },
          { n: 37, title: "The Effects of Pain or Sorrow", articles: 4 },
          { n: 38, title: "The Remedies of Sorrow or Pain", articles: 5 },
          { n: 39, title: "The Goodness and Evil of Sorrow", articles: 4 },
          { n: 40, title: "The Irascible Passions: Hope and Despair", articles: 8 },
          { n: 41, title: "Fear in Itself", articles: 4 },
          { n: 42, title: "The Object of Fear", articles: 6 },
          { n: 43, title: "The Cause of Fear", articles: 2 },
          { n: 44, title: "The Effects of Fear", articles: 4 },
          { n: 45, title: "Daring", articles: 4 },
          { n: 46, title: "Anger in Itself", articles: 8 },
          { n: 47, title: "The Cause of Anger", articles: 4 },
          { n: 48, title: "The Effects of Anger", articles: 4 },
        ],
      },
      {
        label: "Treatise on Habits",
        questions: [
          { n: 49, title: "Habits in General", articles: 4 },
          { n: 50, title: "The Subject of Habits", articles: 6 },
          { n: 51, title: "The Cause of Habits as to Their Formation", articles: 4 },
          { n: 52, title: "The Increase of Habits", articles: 3 },
          { n: 53, title: "Corruption and Diminution of Habits", articles: 3 },
          { n: 54, title: "The Distinction of Habits", articles: 4 },
        ],
      },
      {
        label: "Treatise on Virtues",
        questions: [
          { n: 55, title: "The Virtues in General", articles: 4 },
          { n: 56, title: "The Subject of Virtue", articles: 6 },
          { n: 57, title: "Intellectual Virtues", articles: 6 },
          { n: 58, title: "Moral Virtue", articles: 5 },
          { n: 59, title: "Moral Virtue in Relation to the Passions", articles: 5 },
          { n: 60, title: "How Moral Virtues Differ from One Another", articles: 5 },
          { n: 61, title: "Cardinal Virtues", articles: 5 },
          { n: 62, title: "Theological Virtues", articles: 4 },
          { n: 63, title: "The Cause of Virtues", articles: 4 },
          { n: 64, title: "The Mean of Virtue", articles: 4 },
          { n: 65, title: "The Connection of Virtues", articles: 5 },
          { n: 66, title: "Equality Among the Virtues", articles: 6 },
          { n: 67, title: "The Duration of Virtues After This Life", articles: 6 },
          { n: 68, title: "The Gifts of the Holy Spirit", articles: 8 },
          { n: 69, title: "The Beatitudes", articles: 4 },
          { n: 70, title: "The Fruits of the Holy Spirit", articles: 4 },
        ],
      },
      {
        label: "Treatise on Vices and Sins",
        questions: [
          { n: 71, title: "Vice and Sin in General", articles: 6 },
          { n: 72, title: "The Distinction of Sins", articles: 9 },
          { n: 73, title: "The Comparison of One Sin with Another", articles: 10 },
          { n: 74, title: "The Subject of Sin", articles: 10 },
          { n: 75, title: "The Causes of Sin in General", articles: 4 },
          { n: 76, title: "The Causes of Sin: Ignorance", articles: 4 },
          { n: 77, title: "The Cause of Sin: Passion", articles: 8 },
          { n: 78, title: "The Cause of Sin: Malice", articles: 4 },
          { n: 79, title: "External Causes of Sin: God", articles: 4 },
          { n: 80, title: "External Causes of Sin: The Devil", articles: 4 },
          { n: 81, title: "Original Sin in General", articles: 5 },
          { n: 82, title: "The Essence of Original Sin", articles: 4 },
          { n: 83, title: "The Subject of Original Sin", articles: 4 },
          { n: 84, title: "The Cause of Sin: The Capital Vices", articles: 4 },
          { n: 85, title: "The Effects of Sin: Corruption of Natural Good", articles: 6 },
          { n: 86, title: "The Stain of Sin", articles: 2 },
          { n: 87, title: "The Debt of Punishment", articles: 8 },
          { n: 88, title: "Venial and Mortal Sin", articles: 6 },
          { n: 89, title: "Venial Sin in Itself", articles: 6 },
        ],
      },
      {
        label: "Treatise on Law",
        questions: [
          { n: 90, title: "The Essence of Law", articles: 4 },
          { n: 91, title: "The Various Kinds of Law", articles: 6 },
          { n: 92, title: "The Effects of Law", articles: 2 },
          { n: 93, title: "The Eternal Law", articles: 6 },
          { n: 94, title: "The Natural Law", articles: 6 },
          { n: 95, title: "Human Law", articles: 4 },
          { n: 96, title: "The Power of Human Law", articles: 6 },
          { n: 97, title: "Change in Laws", articles: 4 },
          { n: 98, title: "The Old Law", articles: 6 },
          { n: 99, title: "The Precepts of the Old Law", articles: 6 },
          { n: 100, title: "The Moral Precepts of the Old Law", articles: 12 },
          { n: 101, title: "The Ceremonial Precepts in Themselves", articles: 4 },
          { n: 102, title: "The Causes of the Ceremonial Precepts", articles: 6 },
          { n: 103, title: "The Duration of the Ceremonial Precepts", articles: 4 },
          { n: 104, title: "The Judicial Precepts", articles: 4 },
          { n: 105, title: "The Reason for the Judicial Precepts", articles: 4 },
          { n: 106, title: "The Law of the Gospel: The New Law", articles: 4 },
          { n: 107, title: "Comparison of the New and the Old Law", articles: 4 },
          { n: 108, title: "Things Contained in the New Law", articles: 4 },
        ],
      },
      {
        label: "Treatise on Grace",
        questions: [
          { n: 109, title: "The Necessity of Grace", articles: 10 },
          { n: 110, title: "The Grace of God as Regards Its Essence", articles: 4 },
          { n: 111, title: "The Division of Grace", articles: 5 },
          { n: 112, title: "The Cause of Grace", articles: 5 },
          { n: 113, title: "The Effects of Grace: Justification", articles: 10 },
          { n: 114, title: "Merit", articles: 10 },
        ],
      },
    ],
  },

  {
    id: "secunda-secundae",
    label: "Secunda Secundae",
    abbr: "ST II-II",
    treatises: [
      {
        label: "Treatise on The Theological Virtues",
        questions: [
          { n: 1, title: "Faith", articles: 10 },
          { n: 2, title: "The Act of Faith", articles: 10 },
          { n: 3, title: "The Outward Act of Faith: Confession", articles: 2 },
          { n: 4, title: "The Virtue of Faith Itself", articles: 8 },
          { n: 5, title: "Those Who Have Faith", articles: 4 },
          { n: 6, title: "The Cause of Faith", articles: 2 },
          { n: 7, title: "The Effects of Faith", articles: 2 },
          { n: 8, title: "The Gift of Understanding", articles: 8 },
          { n: 9, title: "The Gift of Knowledge", articles: 4 },
          { n: 10, title: "Unbelief in General", articles: 12 },
          { n: 11, title: "Heresy", articles: 4 },
          { n: 12, title: "Apostasy", articles: 2 },
          { n: 13, title: "The Sin of Blasphemy in General", articles: 4 },
          { n: 14, title: "Blasphemy Against the Holy Ghost", articles: 4 },
          { n: 15, title: "Sins Opposed to Knowledge and Understanding", articles: 3 },
          { n: 16, title: "Precepts of Faith, Knowledge, and Understanding", articles: 2 },
          { n: 17, title: "Hope", articles: 8 },
          { n: 18, title: "The Subject of Hope", articles: 4 },
          { n: 19, title: "The Gift of Fear", articles: 12 },
          { n: 20, title: "Despair", articles: 4 },
          { n: 21, title: "Presumption", articles: 4 },
          { n: 22, title: "Precepts Relating to Hope and Fear", articles: 2 },
          { n: 23, title: "Charity in Itself", articles: 8 },
          { n: 24, title: "The Subject of Charity", articles: 12 },
          { n: 25, title: "The Object of Charity", articles: 12 },
          { n: 26, title: "The Order of Charity", articles: 13 },
          { n: 27, title: "The Principal Act of Charity: Loving", articles: 8 },
          { n: 28, title: "Joy", articles: 4 },
          { n: 29, title: "Peace", articles: 4 },
          { n: 30, title: "Mercy", articles: 4 },
          { n: 31, title: "Beneficence", articles: 4 },
          { n: 32, title: "Almsgiving", articles: 10 },
          { n: 33, title: "Fraternal Correction", articles: 8 },
          { n: 34, title: "Hatred", articles: 6 },
          { n: 35, title: "Sloth", articles: 4 },
          { n: 36, title: "Envy", articles: 4 },
          { n: 37, title: "Discord", articles: 2 },
          { n: 38, title: "Contention", articles: 2 },
          { n: 39, title: "Schism", articles: 4 },
          { n: 40, title: "War", articles: 4 },
          { n: 41, title: "Strife", articles: 2 },
          { n: 42, title: "Sedition", articles: 2 },
          { n: 43, title: "Scandal", articles: 8 },
          { n: 44, title: "Precepts of Charity", articles: 8 },
          { n: 45, title: "The Gift of Wisdom", articles: 6 },
          { n: 46, title: "Folly", articles: 3 },
        ],
      },
      {
        label: "Treatise on The Cardinal Virtues",
        questions: [
          { n: 47, title: "Prudence in Itself", articles: 16 },
          { n: 48, title: "The Parts of Prudence", articles: 1 },
          { n: 49, title: "Each Quasi-Integral Part of Prudence", articles: 8 },
          { n: 50, title: "The Subjective Parts of Prudence", articles: 4 },
          { n: 51, title: "Virtues Connected with Prudence", articles: 4 },
          { n: 52, title: "The Gift of Counsel", articles: 4 },
          { n: 53, title: "Imprudence", articles: 6 },
          { n: 54, title: "Negligence", articles: 3 },
          { n: 55, title: "Vices Opposed to Prudence by Resemblance", articles: 8 },
          { n: 56, title: "Precepts Relating to Prudence", articles: 2 },
          { n: 57, title: "Right and Justice", articles: 4 },
          { n: 58, title: "Justice in General", articles: 12 },
          { n: 59, title: "Injustice", articles: 4 },
          { n: 60, title: "Judgment", articles: 6 },
          { n: 61, title: "The Parts of Justice", articles: 4 },
          { n: 62, title: "Restitution", articles: 8 },
          { n: 63, title: "Respect of Persons", articles: 4 },
          { n: 64, title: "Murder", articles: 8 },
          { n: 65, title: "Injuries to the Person", articles: 4 },
          { n: 66, title: "Theft and Robbery", articles: 9 },
          { n: 67, title: "Injustice in Judgment: The Judge", articles: 4 },
          { n: 68, title: "Injustice in Judgment: Accusation", articles: 4 },
          { n: 69, title: "Injustice in Judgment: The Accused", articles: 4 },
          { n: 70, title: "Injustice in Judgment: The Witnesses", articles: 4 },
          { n: 71, title: "Injustice in Judgment: Advocacy", articles: 4 },
          { n: 72, title: "Reviling", articles: 4 },
          { n: 73, title: "Backbiting", articles: 4 },
          { n: 74, title: "Tale-bearing", articles: 2 },
          { n: 75, title: "Derision", articles: 2 },
          { n: 76, title: "Cursing", articles: 4 },
          { n: 77, title: "Fraud in Buying and Selling", articles: 4 },
          { n: 78, title: "Usury", articles: 4 },
          { n: 79, title: "The Quasi-Integral Parts of Justice", articles: 4 },
          { n: 80, title: "The Potential Parts of Justice", articles: 1 },
          { n: 81, title: "Religion", articles: 8 },
          { n: 82, title: "Devotion", articles: 4 },
          { n: 83, title: "Prayer", articles: 17 },
          { n: 84, title: "Adoration", articles: 3 },
          { n: 85, title: "Sacrifice", articles: 4 },
          { n: 86, title: "Oblations and First-Fruits", articles: 4 },
          { n: 87, title: "Tithes", articles: 4 },
          { n: 88, title: "Vows", articles: 12 },
          { n: 89, title: "Oaths", articles: 10 },
          { n: 90, title: "Adjuration", articles: 3 },
          { n: 91, title: "Taking God's Name for Praise", articles: 2 },
          { n: 92, title: "Superstition", articles: 2 },
          { n: 93, title: "Undue Worship of the True God", articles: 2 },
          { n: 94, title: "Idolatry", articles: 4 },
          { n: 95, title: "Superstition in Divinations", articles: 8 },
          { n: 96, title: "Superstition in Observances", articles: 4 },
          { n: 97, title: "The Temptation of God", articles: 4 },
          { n: 98, title: "Perjury", articles: 4 },
          { n: 99, title: "Sacrilege", articles: 4 },
          { n: 100, title: "Simony", articles: 6 },
          { n: 101, title: "Piety", articles: 4 },
          { n: 102, title: "Observance and Honor", articles: 3 },
          { n: 103, title: "Dulia", articles: 4 },
          { n: 104, title: "Obedience", articles: 6 },
          { n: 105, title: "Disobedience", articles: 2 },
          { n: 106, title: "Gratitude", articles: 6 },
          { n: 107, title: "Ingratitude", articles: 4 },
          { n: 108, title: "Vengeance", articles: 4 },
          { n: 109, title: "Truth", articles: 4 },
          { n: 110, title: "Lying", articles: 4 },
          { n: 111, title: "Simulation and Hypocrisy", articles: 4 },
          { n: 112, title: "Boasting", articles: 2 },
          { n: 113, title: "Irony", articles: 2 },
          { n: 114, title: "Affability", articles: 2 },
          { n: 115, title: "Flattery", articles: 2 },
          { n: 116, title: "Quarreling", articles: 2 },
          { n: 117, title: "Liberality", articles: 6 },
          { n: 118, title: "Covetousness", articles: 8 },
          { n: 119, title: "Prodigality", articles: 3 },
          { n: 120, title: "Epikeia", articles: 2 },
          { n: 121, title: "Piety as Part of Justice", articles: 2 },
          { n: 122, title: "Precepts of Justice", articles: 6 },
        ],
      },
      {
        label: "Treatise on Fortitude and Temperance",
        questions: [
          { n: 123, title: "Fortitude", articles: 12 },
          { n: 124, title: "Martyrdom", articles: 5 },
          { n: 125, title: "Fear", articles: 4 },
          { n: 126, title: "Fearlessness", articles: 2 },
          { n: 127, title: "Daring", articles: 2 },
          { n: 128, title: "The Parts of Fortitude", articles: 1 },
          { n: 129, title: "Magnanimity", articles: 8 },
          { n: 130, title: "Presumption", articles: 2 },
          { n: 131, title: "Ambition", articles: 2 },
          { n: 132, title: "Vainglory", articles: 5 },
          { n: 133, title: "Pusillanimity", articles: 2 },
          { n: 134, title: "Magnificence", articles: 4 },
          { n: 135, title: "Meanness", articles: 2 },
          { n: 136, title: "Patience", articles: 5 },
          { n: 137, title: "Perseverance", articles: 4 },
          { n: 138, title: "Vices Opposed to Perseverance", articles: 2 },
          { n: 139, title: "The Gift of Fortitude", articles: 2 },
          { n: 140, title: "Precepts of Fortitude", articles: 2 },
          { n: 141, title: "Temperance", articles: 8 },
          { n: 142, title: "Vices Opposed to Temperance", articles: 4 },
          { n: 143, title: "The Parts of Temperance in General", articles: 1 },
          { n: 144, title: "Shamefacedness", articles: 4 },
          { n: 145, title: "Honesty", articles: 4 },
          { n: 146, title: "Abstinence", articles: 2 },
          { n: 147, title: "Fasting", articles: 8 },
          { n: 148, title: "Gluttony", articles: 6 },
          { n: 149, title: "Sobriety", articles: 4 },
          { n: 150, title: "Drunkenness", articles: 4 },
          { n: 151, title: "Chastity", articles: 4 },
          { n: 152, title: "Virginity", articles: 5 },
          { n: 153, title: "Lust", articles: 5 },
          { n: 154, title: "The Parts of Lust", articles: 12 },
          { n: 155, title: "Continence", articles: 4 },
          { n: 156, title: "Incontinence", articles: 4 },
          { n: 157, title: "Clemency and Meekness", articles: 4 },
          { n: 158, title: "Anger", articles: 8 },
          { n: 159, title: "Cruelty", articles: 2 },
          { n: 160, title: "Modesty", articles: 2 },
          { n: 161, title: "Humility", articles: 6 },
          { n: 162, title: "Pride", articles: 8 },
          { n: 163, title: "The First Man's Sin", articles: 4 },
          { n: 164, title: "The Punishment of the First Man's Sin", articles: 2 },
          { n: 165, title: "The Temptation of Our First Parents", articles: 2 },
          { n: 166, title: "Studiousness", articles: 2 },
          { n: 167, title: "Curiosity", articles: 2 },
          { n: 168, title: "Modesty as to Outward Movements", articles: 4 },
          { n: 169, title: "Modesty in Outward Apparel", articles: 2 },
          { n: 170, title: "Precepts of Temperance", articles: 2 },
        ],
      },
      {
        label: "Treatise on Gratuitous Graces",
        questions: [
          { n: 171, title: "Prophecy", articles: 6 },
          { n: 172, title: "The Cause of Prophecy", articles: 6 },
          { n: 173, title: "The Mode of Prophetic Knowledge", articles: 4 },
          { n: 174, title: "The Division of Prophecy", articles: 6 },
          { n: 175, title: "Rapture", articles: 6 },
          { n: 176, title: "The Grace of Tongues", articles: 2 },
          { n: 177, title: "Graces of Speech", articles: 2 },
          { n: 178, title: "The Grace of Miracles", articles: 2 },
          { n: 179, title: "The Active and Contemplative Life: Division", articles: 2 },
          { n: 180, title: "The Contemplative Life", articles: 8 },
          { n: 181, title: "The Active Life", articles: 4 },
          { n: 182, title: "Comparison of the Active and Contemplative Life", articles: 4 },
        ],
      },
      {
        label: "Treatise on The States of Life",
        questions: [
          { n: 183, title: "Man's Various Duties and States in General", articles: 4 },
          { n: 184, title: "Perfection in General", articles: 8 },
          { n: 185, title: "Things Pertaining to the Episcopal State", articles: 8 },
          { n: 186, title: "The Religious State and Perfection", articles: 10 },
          { n: 187, title: "Things Befitting Religious", articles: 6 },
          { n: 188, title: "The Different Kinds of Religious Life", articles: 8 },
          { n: 189, title: "The Entry into Religious Life", articles: 10 },
        ],
      },
    ],
  },

  {
    id: "tertia-pars",
    label: "Tertia Pars",
    abbr: "ST III",
    treatises: [
      {
        label: "Treatise on The Incarnation",
        questions: [
          { n: 1, title: "The Fitness of the Incarnation", articles: 6 },
          { n: 2, title: "The Mode of Union of the Incarnate Word", articles: 12 },
          { n: 3, title: "The Mode of Union as Regards the Person Assuming", articles: 8 },
          { n: 4, title: "The Mode of Union as Regards the Human Nature Assumed", articles: 6 },
          { n: 5, title: "Parts of Human Nature Assumed by Christ", articles: 4 },
          { n: 6, title: "Order of Assumption", articles: 6 },
          { n: 7, title: "Grace of Christ as an Individual Man", articles: 13 },
          { n: 8, title: "Grace of Christ as the Head of the Church", articles: 8 },
          { n: 9, title: "Christ's Knowledge in General", articles: 4 },
          { n: 10, title: "The Beatific Knowledge of Christ's Soul", articles: 4 },
          { n: 11, title: "Knowledge Infused into Christ's Soul", articles: 6 },
          { n: 12, title: "Acquired Knowledge of Christ's Soul", articles: 4 },
          { n: 13, title: "The Power of Christ's Soul", articles: 4 },
          { n: 14, title: "Defects of Body Assumed by Christ", articles: 4 },
          { n: 15, title: "Defects of Soul Assumed by Christ", articles: 10 },
          { n: 16, title: "Things That Can Be Said of Christ", articles: 12 },
          { n: 17, title: "Christ's Unity of Being", articles: 2 },
          { n: 18, title: "Christ's Unity of Will", articles: 6 },
          { n: 19, title: "Unity of Operation in Christ", articles: 4 },
          { n: 20, title: "Christ's Subjection to the Father", articles: 2 },
          { n: 21, title: "Christ's Prayer", articles: 4 },
          { n: 22, title: "Christ's Priesthood", articles: 6 },
          { n: 23, title: "Adoption as Sons of God", articles: 4 },
          { n: 24, title: "The Predestination of Christ", articles: 4 },
          { n: 25, title: "Adoration of Christ", articles: 6 },
          { n: 26, title: "Christ as Mediator", articles: 2 },
          { n: 27, title: "The Sanctification of the Blessed Virgin Mary", articles: 6 },
          { n: 28, title: "The Virginity of the Mother of God", articles: 4 },
          { n: 29, title: "The Espousal of the Virgin Mother", articles: 2 },
          { n: 30, title: "The Annunciation of the Incarnation", articles: 4 },
          { n: 31, title: "The Matter from Which the Son of God Was Conceived", articles: 8 },
          { n: 32, title: "The Active Principle in Christ's Conception", articles: 4 },
          { n: 33, title: "The Mode and Order of Christ's Conception", articles: 4 },
          { n: 34, title: "The Perfection of the Conceived Child", articles: 4 },
          { n: 35, title: "Christ's Nativity", articles: 8 },
          { n: 36, title: "The Manifestation of the Newly Born Christ", articles: 8 },
          { n: 37, title: "Christ's Circumcision and Other Legal Observances", articles: 4 },
          { n: 38, title: "The Baptism of John", articles: 6 },
          { n: 39, title: "The Baptism of Christ", articles: 8 },
          { n: 40, title: "Christ's Manner of Life", articles: 4 },
          { n: 41, title: "Christ's Temptation", articles: 4 },
          { n: 42, title: "Christ's Doctrine and Teaching", articles: 4 },
          { n: 43, title: "The Miracles Wrought by Christ in General", articles: 4 },
          { n: 44, title: "Each of Christ's Miracles in Particular", articles: 4 },
          { n: 45, title: "The Transfiguration of Christ", articles: 4 },
          { n: 46, title: "The Passion of Christ", articles: 12 },
          { n: 47, title: "The Efficient Cause of Christ's Passion", articles: 6 },
          { n: 48, title: "How Christ's Passion Wrought Our Deliverance", articles: 6 },
          { n: 49, title: "The Effects of Christ's Passion", articles: 6 },
          { n: 50, title: "The Death of Christ", articles: 6 },
          { n: 51, title: "Christ's Burial", articles: 4 },
          { n: 52, title: "Christ's Descent into Hell", articles: 8 },
          { n: 53, title: "Christ's Resurrection", articles: 4 },
          { n: 54, title: "The Quality of Christ's Risen Body", articles: 4 },
          { n: 55, title: "The Manifestation of the Resurrection", articles: 6 },
          { n: 56, title: "The Causality of Christ's Resurrection", articles: 2 },
          { n: 57, title: "The Ascension of Christ", articles: 6 },
          { n: 58, title: "Christ's Sitting at the Right Hand of the Father", articles: 4 },
          { n: 59, title: "Christ's Judiciary Power", articles: 6 },
        ],
      },
      {
        label: "Treatise on The Sacraments",
        questions: [
          { n: 60, title: "What is a Sacrament", articles: 8 },
          { n: 61, title: "The Necessity of the Sacraments", articles: 4 },
          { n: 62, title: "The Principal Effect of Sacraments: Grace", articles: 6 },
          { n: 63, title: "The Other Effect of Sacraments: A Character", articles: 6 },
          { n: 64, title: "The Causes of Sacraments", articles: 10 },
          { n: 65, title: "The Number of the Sacraments", articles: 4 },
          { n: 66, title: "Baptism", articles: 12 },
          { n: 67, title: "The Ministers of Baptism", articles: 8 },
          { n: 68, title: "Those Who Receive Baptism", articles: 12 },
          { n: 69, title: "The Effects of Baptism", articles: 10 },
          { n: 70, title: "Circumcision", articles: 4 },
          { n: 71, title: "Preparation for Baptism: Catechism and Exorcism", articles: 4 },
          { n: 72, title: "The Sacrament of Confirmation", articles: 12 },
          { n: 73, title: "The Eucharist in General", articles: 6 },
          { n: 74, title: "The Matter of the Eucharist", articles: 8 },
          { n: 75, title: "Transubstantiation", articles: 8 },
          { n: 76, title: "The Body of Christ in the Eucharist", articles: 8 },
          { n: 77, title: "The Accidents of the Bread and Wine in the Eucharist", articles: 8 },
          { n: 78, title: "The Form of the Eucharist", articles: 6 },
          { n: 79, title: "The Effects of the Eucharist", articles: 8 },
          { n: 80, title: "The Use or Reception of the Eucharist", articles: 12 },
          { n: 81, title: "How Christ Used This Sacrament at the Last Supper", articles: 4 },
          { n: 82, title: "The Minister of the Eucharist", articles: 10 },
          { n: 83, title: "The Rite of the Eucharist", articles: 6 },
          { n: 84, title: "The Sacrament of Penance", articles: 10 },
          { n: 85, title: "Penance as a Virtue", articles: 6 },
          { n: 86, title: "The Effect of Penance: Forgiveness of Mortal Sin", articles: 6 },
          { n: 87, title: "The Remission of Venial Sins by Penance", articles: 4 },
          { n: 88, title: "Return of Sins Forgiven by Penance", articles: 4 },
          { n: 89, title: "Recovery of Virtue by Means of Penance", articles: 6 },
          { n: 90, title: "The Parts of Penance in General", articles: 4 },
        ],
      },
    ],
  },
];
